white_jokes = [
    {"joke": "Why did the scarecrow win an award? \nBecause he was outstanding in his field! 🌾😂"},
    {"joke": "Why don't skeletons fight each other? \nBecause they don’t have the guts! ☠️🤣"},
    {"joke": "I told my wife she should embrace her mistakes. \nShe gave me a hug. 😅😂"},
    {"joke": "Why do cows wear bells? \nBecause their horns don’t work! 🐄🔔🤣"},
    {"joke": "What do you call fake spaghetti? \nAn impasta! 🍝😂"},
    {"joke": "Why did the golfer bring two pairs of pants? \nIn case he got a hole in one! ⛳😂"},
    {"joke": "What did the janitor say when he jumped out of the closet? \nSupplies! 🧹😂"},
    {"joke": "I would tell you a chemistry joke, \nbut I know I wouldn't get a reaction. ⚗️🤣"},
    {"joke": "Why couldn’t the bicycle stand up by itself? \nBecause it was two-tired! 🚴😂"},
    {"joke": "What did one wall say to the other wall? \nI'll meet you at the corner! 🏠🤣"},
    {"joke": "Why don't eggs tell jokes? \nBecause they might crack up! 🥚😂"},
    {"joke": "Why was the math book sad? \nBecause it had too many problems. 📖🤣"},
    {"joke": "Did you hear about the kidnapping at school? \nIt’s fine now, he woke up! 😂"},
    {"joke": "What do you call cheese that isn’t yours? \nNacho cheese! 🧀🤣"},
    {"joke": "Why don’t oysters share their pearls? \nBecause they’re shellfish! 🦪😂"},
    {"joke": "What do you call a factory that makes good products? \nA satisfactory! 🏭😂"},
    {"joke": "Why did the cookie cry? \nBecause his mom was a wafer too long! 🍪😂"},
    {"joke": "What’s orange and sounds like a parrot? \nA carrot! 🥕😂"},
    {"joke": "Why did the tomato blush? \nBecause it saw the salad dressing! 🍅🤣"},
    {"joke": "How do you organize a space party? \nYou planet! 🚀😂"},
    {"joke": "Why did the football coach go to the bank? \nTo get his quarterback! 🏈🤣"},
    {"joke": "What’s the best way to watch a fly fishing tournament? \nLive stream it! 🎣😂"},
    {"joke": "Why don’t seagulls fly over the bay? \nBecause then they’d be called bagels! 🥯😂"},
    {"joke": "What’s brown and sticky? \nA stick! 🌿🤣"},
    {"joke": "I told my suitcase there will be no vacations this year. \nNow I’m dealing with emotional baggage! 🎒😂"},
    {"joke": "What do you call an alligator in a vest? \nAn investigator! 🐊😂"},
    {"joke": "Why don’t crabs give to charity? \nBecause they’re shellfish! 🦀🤣"},
    {"joke": "Why do trees seem suspicious on sunny days? \nThey just seem a little shady! 🌳😂"},
    {"joke": "What kind of shoes do ninjas wear? \nSneakers! 👟🤣"},
    {"joke": "Why did the chicken go to the séance? \nTo talk to the other side! 🐔😂"},
]

desi_jokes = [
    {"joke": "Biwi: Tum mujhse kitna pyaar karte ho? \nShauhar: Itna zyada ki free mein bhi shadi kar leta! 💘😂"},
    {"joke": "Teacher: Pakistan ka sabse bada masla kya hai? \nStudent: Sir, 'Load Shedding' aur 'Doodh mein pani'! ⚡🥛🤣"},
    {"joke": "Pathan: Bhai, mehenga petrol ka kia tareeqa hai? \nDost: Tank full karwao, aur gari bech do! ⛽😂"},
    {"joke": "Boy: Mujhe bhi English seekhni hai! \nFriend: Start kar! \nBoy: 'Kya start kar'? \nFriend: Bas beta, rehne de! 🤣"},
    {"joke": "Chor ghar mein ghusa, likha tha: 'Main bhi dekh raha hoon!' \nChor dara, dekha toh papita likha tha! 😂"},
    {"joke": "Customer: Yeh anday fresh hain? \nDukaan wala: Bhai, murghi ne khud la kar diye hain! 🥚🤣"},
    {"joke": "Larka: Papa, mujhe shadi karni hai! \nPapa: Kya ladki pasand hai? \nLarka: Nai, sirf shadi ka khayal achha lag raha hai! 😂"},
    {"joke": "Pathan bus conductor bana, \nPassenger: Bhai, Nazimabad aa gaya? \nPathan: Tumhein nazar nahi aa raha? 😆"},
    {"joke": "Doctor: Yeh kaise lagi? \nPathan: Biwi ka call aya, sir hilaya, truck se takkar ho gayi! 🚑🤣"},
    {"joke": "Teacher: Mobile ka istemal mat karo! \nStudent: Sir, Google meri maa hai! 😂"},
    {"joke": "Biwi: Tum mujhe kab surprise doge? \nMian: Jab tum kapray dho rahi hogi, aur main bolun washing machine kharab hai! 🤣"},
    {"joke": "Saas: Tum roti gol kyun nahi bana sakti? \nBahu: Maa, duniya gol nahi, chakkar hai! 😂"},
    {"joke": "Boy: Tumhara favorite color? \nGirl: Pink! \nBoy: Tumhari shadi ho gayi? \nGirl: Nahi! \nBoy: Toh fir red ho jao! 💘🤣"},
    {"joke": "Boy: Tum mujhe pasand karti ho? \nGirl: Nahi! \nBoy: Achha, chalo maa se keh sakta hoon, koi pasand nahi! 😂"},
    {"joke": "Teacher: Pani ka formula kya hai? \nStudent: H2O! \nTeacher: Aur garam pani ka? \nStudent: H2O O O O O! 💦🤣"},
    {"joke": "Pathan: Tumhare mobile ka password kya hai? \nDost: Beta ka naam! \nPathan: Mere paas beta nahi, ab kya karoon? 😆"},
    {"joke": "Customer: Yeh shirt kitne ki hai? \nShopkeeper: 500 rupees! \nCustomer: Bhai 200 mein do! \nShopkeeper: 200 ka sirf button aayega! 🧥🤣"},
    {"joke": "Boy: Bhai, mera phone nahi mil raha! \nFriend: Kis number pe call kiya? \nBoy: Apne phone se hi call kiya tha! 📱😂"},
    {"joke": "Pathan ke ghar mehmaan aaya, \nPathan bola: Coffee ya chai? \nMehmaan: Jo bhi ho! \nPathan: Toh phir khud bana lo! ☕😂"},
    {"joke": "Teacher: Mohabbat aur dosti mein kya farq hai? \nStudent: Sir, Free Fire aur PUBG mein jo farq hai! 🎮🤣"},
    {"joke": "Ammi: Beta, copy pe kya likha hai? \nBeta: Mama, yeh formula hai! \nAmmi: Formula nahi, teri handwriting hai! 📖😂"},
    {"joke": "Boy: Aap shaadi ke liye ready hain? \nGirl: Bhai, pehle ghar se permission le lo! \nBoy: Ghar pe baat ki, unka bhi 'no' hai! 😂"},
    {"joke": "Boy: Tum mujhe pasand karti ho? \nGirl: Nahi! \nBoy: Chalo acha hai, ab mama se keh sakta hoon mujhe koi pasand nahi! 🤣"},
    {"joke": "Doctor: Beta, itna tension mat lo! \nPatient: Phir EMI kaun dega? 😂"},
    {"joke": "Saas: Kya banaya hai? \nBahu: Aloo! \nSaas: Kya kiya hai aloo ka? \nBahu: Samosay banaye! 🥔🤣"},
    {"joke": "Larki: Mere walid tumse milna chahte hain! \nLarka: Kyun? \nLarki: Kyunki tum unke beta bann sakte ho! 😂"},
    {"joke": "Teacher: Chawal ka plural batao? \nStudent: Plate! 🍚🤣"},
    {"joke": "Boy: Tumhara favorite color? \nGirl: Pink! \nBoy: Tumhari shadi ho gayi? \nGirl: Nahi! \nBoy: Toh fir red ho jao! 😂"},
    {"joke": "Boy: Kya tumhari shadi fix ho gayi? \nFriend: Nai yaar! \nBoy: Phir itna fresh kyun lag raha hai? 🤣"},
    {"joke": "Biwi: Tum mujhe shopping pe le jaoge? \nShauhar: Tumhari tabiyat to theek hai? \nBiwi: Haan! \nShauhar: Toh phir ghar baitho! 🤣"},
]
